INCLUDES += -I$(RIOTCPU)/mips32r2_common/include

export USEMODULE += mips32r2_common
export USEMODULE += mips32r2_common_periph
export USEMODULE += newlib

ifeq ($(USE_UHI_SYSCALLS),1)
  #Use UHI to handle syscalls
  LINKFLAGS += -luhi
  export USEMODULE += newlib_syscalls_mips_uhi
  CFLAGS += -DHAVE_HEAP_STATS
else
  #Use RIOT to handle syscalls (default)
  export USEMODULE += newlib_syscalls_default
endif
